# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres           # Default value
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb                 # Default value is value of POSTGRES_USER
      PGDATA: /var/lib/postgresql/data  # Default value

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080